@foodswap_HostAddress = http://localhost:5256

###
GET {{foodswap_HostAddress}}/foods
Accept: application/json

###
GET {{foodswap_HostAddress}}/foods/7f6d3aba-4391-4138-bca2-5175c1137475
Accept: application/json

###
POST {{foodswap_HostAddress}}/foods
Accept: application/json
Content-Type: application/json

{
  "name": "asda",
  "portion": 100,
  "calories": 10,
  "carbohydrates": 20,
  "protein": 30,
  "fat": 40,
  "type": "MEAT"
}

###
POST {{foodswap_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "name": "John",
  "surname": "Doe",
  "email": "john.doe@example",
  "password": "StrongPassword123!",
  "phoneNumber": "11987654321",
  "birthDate": "1990-05-15T00:00:00"
}